import IISAvtomatizaciya_Prodazhi2ЗакПокупEController from '../i-i-s-avtomatizaciya-prodazhi2-зак-покуп-e';

var IISAvtomatizaciya_Prodazhi2ЗакПокупENewController = IISAvtomatizaciya_Prodazhi2ЗакПокупEController;
export default IISAvtomatizaciya_Prodazhi2ЗакПокупENewController;
