import IISAvtomatizaciya_Prodazhi2ОрганизEController from '../i-i-s-avtomatizaciya-prodazhi2-организ-e';

var IISAvtomatizaciya_Prodazhi2ОрганизENewController = IISAvtomatizaciya_Prodazhi2ОрганизEController;
export default IISAvtomatizaciya_Prodazhi2ОрганизENewController;
